### ISSUE TITLE
Fail to reshape 0-length array

### ISSUE THREAD

**Issue by pentschev** [pydata/sparse#254]
@hameerabbasi as per our discussion in https://github.com/dask/dask/pull/4543:

```python
>>> import numpy as np
>>> import sparse
>>> a = sparse.COO.from_numpy(np.empty((0, 0, 0)))
>>> a.reshape((-1, 0))
/home/pentschev/miniconda3/envs/rapids/lib/python3.6/site-packages/sparse/coo/core.py:1702: RuntimeWarning: invalid value encountered in long_scalars
  np.prod([d for d in shape if d != -1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pentschev/miniconda3/envs/rapids/lib/python3.6/site-packages/sparse/coo/core.py", line 1702, in reshape
    np.prod([d for d in shape if d != -1]))
ValueError: cannot convert float NaN to integer
```

If you want I can submit a PR in a couple of weeks, otherwise, feel free to tackle this. :)

**Comment by hameerabbasi** [comment]
Okay, so I investigated the cause of the issue here. This is an ambiguous operation in general: Even NumPy has this issue:
```python
>>> import numpy as np
>>> a = np.empty((0, 0, 0))
>>> a.reshape((-1, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot reshape array of size 0 into shape (0)
```

The reason is that the value to be "filled in" at `-1` can be any non-negative integer...
```
Errors should never pass silently.
In the face of ambiguity, refuse the temptation to guess.
```

So I guess the conclusion is: You shouldn't be doing reshapes with `-1` in them on zero-sized arrays?

So there are a couple of options here:
1. You mean reshaping a zero-size array to `(-1,)`, which already works on `master`.
2. You want a different error message (in which case feel free to re-open and say so :smile:)

**Comment by pentschev** [comment]
Sorry, I should have been more specific as to the origin of this issue. Indeed, I didn't check whether `reshape` supported that in NumPy, if I was trying to do that operation directly, I would have probably catched this behavior in NumPy. However, this issue arises on the use of `tensordot`, that probably has a different internal implementation than NumPy. I'll file a different issue for that, instead of rewriting this one.
