### ISSUE TITLE
How to get the diagnonal?

### ISSUE THREAD

**Issue by rabernat** [pydata/sparse#259]
I am trying out sparse for the first time. Thanks for making it!

I want to get the diagonal of a sparse matrix, but I can't figure out how! In scipy.sparse I would just call [`diagonal`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.diagonal.html), but sparse doesn't have this method.

Thanks for your advice.

**Comment by hameerabbasi** [comment]
Hello! I see you're from the Pangeo team!

Currently, there's no way, but I can work on adding one.

**Comment by rabernat** [comment]
I guess a more general question would be...what is the API that sparse aims to implement? Is the goal to emulate the scipy.sparse API? The Roadmaps says 

> Our eventual aim is to cover all areas of NumPy where algorithms exist that give sparse arrays an edge over dense arrays.

But also that

> PyData/Sparse is well on its way to replacing scipy.sparse as the de-facto sparse array implementation in the PyData ecosystem.

Replacing scipy.sparse would require also implementing most of the scipy.sparse API.

Having clarity about this from the dev could help people decide whether they want to built on sparse vs scipy.sparse.

**Comment by rgommers** [comment]
> Replacing scipy.sparse would require also implementing most of the scipy.sparse API.

Not the `scipy.sparse` API, because that's exactly what we'd like to see replaced with a sparse `numpy.ndarray`-compatible API. But the big missing piece here is `scipy.sparse.linalg` working with `pydata/sparse`. 

> Having clarity about this from the devs could help people decide whether they want to built on sparse vs scipy.sparse.

If you don't need linear algebra functionality, then `pydata/sparse` is probably the best bet medium to long term. For short term, it depends on whether `pydata/sparse` is feature-complete and performant enough for you today - best to just try that out. If you're missing methods, those should be easy to add. If performance is an issue, we'd like to know.

**Comment by rabernat** [comment]
Gotcha, thanks for the update.

I personally do rely on the scipy.sparse.linalg functions in quite a few places.

For now my workaround for getting the diagnonal is
```python
diag = np.array([S[n,n] for n in range(S.shape[0])])
```

which works absolutely fine on a matrix of shape 20000 x 20000

**Comment by hameerabbasi** [comment]
This is now done: #289
