### ISSUE TITLE
Calculate Pairwise Pearson Correlation with Sparse Matrix

### ISSUE THREAD

**Issue by seanlaw** [pydata/sparse#262]
I have a fairly large sparse matrix that I would like to compute the pairwise Pearson correlation coefficients for using Dask Distributed. 

```
from dask.distributed import Client, wait
import scipy.sparse
import sparse  # Need to install this on dask cluster!
import dask.array as da
import dask

client = Client('tcp://some_host:8786')  # Contains 32 cores, 300 GB RAM total

csr = scipy.sparse.random(3000000, 5000, density=0.20)
s = sparse.COO.from_scipy_sparse(csr)
x = da.from_array(s, chunks=(1000, 1000), asarray=False)
x = client.persist(x) 
futures = wait(x)

y = da.corrcoef(x)
z = y > 0.9
z = z.map_blocks(sparse.COO.from_numpy)
z = da.triu(z, k=1)

z.compute()
```

Upon executing `z.compute()` I get:

`RuntimeError: Cannot convert a sparse array to dense automatically. To manually densify, use the todense method.`

Ultimately, I don't even need the actual Pearson correlation coefficients. What I am interested in is returning a sparse matrix (**not** a dense matrix) that have values of 1.0 where the computed Pearson correlation is greater than 0.9. 

Is this possible using `sparse` and `dask.distributed`?

**Comment by hameerabbasi** [comment]
1. If the density is really 0.2, I would suggest you use dense matrices.
2. I suspect the issue is on this line of Dask: https://github.com/dask/dask/blob/2f55cf432ab4334e7ed6b03e62dc169e4208b33e/dask/array/routines.py#L792

It is algorithmically correct but requires a definition of `dot` that works sparse matrices with a non-zero fill value. Let me ask this: Are you fairly sure that the data is already close to zero-mean when it is sparse? If so, you can use covariance instead of correlation and manually write out the formulas, and that will already work.

If not, a definition of non-zero-fill-value-`dot` will be required. It's technically possible but not very nice.

**Comment by seanlaw** [comment]
I tried out a more explicit approach following [this implementation](https://gist.github.com/twiecki/030aa8565bae9e7ca37e3e789b6eeead) and am now getting what appears to be a more explicit error:

```
/app/home/miniconda3/lib/python3.7/site-packages/sparse/coo/common.py in concatenate()

/app/home/miniconda3/lib/python3.7/site-packages/sparse/utils.py in check_consistent_fill_value()

ValueError: This operation requires consistent fill-values, but argument 1 had a fill value of nan, which is different from a fill_value of 0.0 in the first argument.
```
I assume that it is what you were referring to. 

> If so, you can use covariance instead of correlation and manually write out the formulas, and that will already work.

I'm not sure I fully understand. Is there a reference implementation/pseudocode that you can point me to?

**Comment by hameerabbasi** [comment]
Ahh. It seems you're introducing `NaN`s in your data, which is almost always a bad thing. A fill value means a value we're "not storing" instead of zero. Somewhere along the line, you did something like Square root of a negative number or zero divided by zero... And this means that your fill-value is no longer zero when concatenating. I'm assuming this is an error in your input data, and the error is before this implementation even came into play.

**Comment by seanlaw** [comment]
It looks like the `NaN`s are coming are coming from the correlation implementation that I had referenced above. Specifically, the `NaN`s seem to come about when it tries to first [normalize the sparse data](https://gist.github.com/twiecki/030aa8565bae9e7ca37e3e789b6eeead#file-dask_sparse_corr-py-L17-L18). I wonder if there is a more meaningful/graceful way to handle that divide by zero?

**Comment by hameerabbasi** [comment]
If the data is zero in the denominator, I would suggest you remove the corresponding rows and columns entirely, as the coefficient is undefined at those points anyway.

**Comment by hameerabbasi** [comment]
The other option (if you're sure none of them are zero) is to use `.todense()` on the denominator.

**Comment by hameerabbasi** [comment]
@seanlaw Did I manage to solve your problem?

**Comment by seanlaw** [comment]
Thanks, @hameerabbasi. Feel free to close this issue. I'm going to write up a [blog](http://seanlaw.github.io/blog.html) post and post the link here afterward.
