### ISSUE TITLE
Is it okay to require a C++ compiler at runtime?

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#310]
I was considering using [`cppyy`](https://cppyy.readthedocs.io/en/latest/) as the C++/Python wrapper as it allows creating runtime bindings. Everything else that can wrap TACO (#299) practically can't create runtime types, and for Numba a re-implementation of all necessary parts would be needed.

For background, the reason we need runtime types is a type explosion within TACO.

**Comment by rgommers** [comment]
Hmm, that sounds like a recipe for user complains. Getting, e.g., every Windows user to install MSVC 2017 is going to be a really hard sell.

Could you make it optional? And when it's not installed, only support operations between sparse arrays with the same format (avoiding the type explosion)?

**Comment by wlav** [comment]
For the fun of it, I once tried on Linux and yes, on that platform anyway, it's possible to ship the precompiled headers with the binary and rely on on Cling's builtin Clang. The precompiled headers would have to be Windows-version specific though, and should NOT be used if there is a system compiler installed. In short, the installation/deployment will need a bunch of hooks to do the correct thing (PCHs are also not small: ~20MB).

That said, I'd be much more worried about mixing with Numba, since both it and cppyy (through Cling) use LLVM. Theoretically, it should work, since Cling encapsulates the parts of LLVM it needs and doesn't expose LLVM symbols, but AFAIK, the combination cppyy+Numba hasn't been tried yet, so it's unknown territory and there may be dragons.

The other question is how do the types "explode"? This is still an open/unresolved issue (intermediate templates that really should be collapsed appearing on the user-side):
   https://bitbucket.org/wlav/cppyy/issues/166/cast-instance-before-it-enters-python

**Comment by rth** [comment]
> Hmm, that sounds like a recipe for user complains. Getting, e.g., every Windows user to install MSVC 2017 is going to be a really hard sell.

Yes, accepting numba/llvmlite as a dependency would already take some discussions for legacy projects traditionally relying on Cython/C extensions. Requiring a C++ compiler at runtime would really be detrimental to adoption, I think, particularly on Windows.

**Comment by hameerabbasi** [comment]
Yes, we decided to use a Python AST construction instead of C/C++, and then use Numba. Unfortunately that means we need a re-write.

**Comment by hameerabbasi** [comment]
@wlav Since you asked, there can be *many* runtime types. Think of `std::vector<std::vector<...>>` but with multiple implementations of `std::vector`.

I'll keep this closed for now, but how about using `conda-forge` as the recommended distribution mechanism? It would, in theory anyway, install all the compilers magically.

For background, Numba's adoption of what they call [`@jitclass`](https://numba.pydata.org/numba-doc/dev/user/jitclass.html) is experimental, and really buggy. See, for instance, numba/numba#4940, numba/numba#4522 and numba/numba#4960.

**Comment by wlav** [comment]
vector of vector etc. isn't a problem per se. Even for auto-conversion, as long as the types are proper. (Or the first one anyway, which is used to match the template of the temporary to generate; the rest is checked upon conversion.) Example:
```
import cppyy
  
cppyy.cppdef("""
    void func(const std::vector<std::vector<std::vector<double>>>& v) {
        for (auto& v1 : v)
            for (auto& v2 : v1) {
                for (auto d : v2)
                    std::cerr << d << " ";
                std::cerr << std::endl;
            }
   }
""")

cppyy.gbl.func((((1., 2, 3), (4., 5, 6)), ((7., 8, 9), (10., 11, 12))))
```
which prints:
```
1 2 3 
4 5 6 
7 8 9 
10 11 12
```
But note that this is "built-out" behavior: cppyy just runs the recursion and does not consider this vector-of-vector-of... as a multi-dimensional array, so it wouldn't auto-convert from e.g. a 3D numpy.ndarray.

As for conda, the problem there is only that above Windows is mentioned as a client, and there isn't a Windows recipe for cppyy on conda yet ... (There's nothing technical to prevent that from happening, since Windows is supported just fine through PyPI, just that none of us has the relevant expertise to write such a recipe.)
