### ISSUE TITLE
Cython for radix argsort and fast indexing?

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#62]
Since our main bottleneck is sorting, I was considering adding Cython as a dev dependency to create a

- Custom radix sort solution.
- Blazing fast indexing (#60)

I was considering this for 0.3.

**Comment by mrocklin** [comment]
No objection from me.  I'll throw out the alternative option of Numba as
well.  Historically the primary reason to avoid numba has been that it
wasn't pip installable.  Now it is.  There may still be other reasons to
avoid this though.  The advantage would be a simpler build process and
staying within Pure Python.  It would be a deviation from community norms
though.

**Comment by hameerabbasi** [comment]
The problem I often have with Numba is its lack of support for many features and the fact that it's limited to a subset of Numpy for fast performance. It does have the advantages of automatic optimization and pure Python, though.

On the other hand, Cython is a superset of Python and can be hand optimized. Of course, I don't have personal experience with either of these, just going off a few blog posts that I read. I'll leave the decision up to you.

**Comment by nils-werner** [comment]
I don't like the way cython are handling the installation and build step ([see cython#477](https://github.com/cython/cython/pull/477)). They require you to `import cython` and put code in your `setup.py`, which creates a chicken-and-egg problem during installation.

I am not saying I am against using cython, as it's probably the best solution. I would just like to see us find a tidy solution that doesn't require weird hacks because of issues we didn't see coming when we started working on this.

**Comment by mrocklin** [comment]
@sklam do you happen to know of (or want to produce) a fast radix sort?  It would be interesting to see what a numba solution would look like here and how much added hassle it would generate.

**Comment by hameerabbasi** [comment]
There are a few implementations on [this SO question](https://stackoverflow.com/questions/34023841/vectorized-radix-sort-with-numpy-can-it-beat-np-sort), particularly [this answer](https://stackoverflow.com/a/34073267/774273). However, these will need to be modified as what we really need is an argsort, rather than a sort.

**Comment by sklam** [comment]
@mrocklin , the only radixsort I used is a GPU implementation from [CUB](http://nvlabs.github.io/cub/structcub_1_1_device_radix_sort.html).  Internally, numba uses quicksort for both `np.sort` and `np.argsort`.

**Comment by mrocklin** [comment]
Can you estimate how hard it would be to build a radix sort in numba?
<nerd snipe> Do you have any interest in doing this as a side project?
</nerd snipe>

**Comment by hameerabbasi** [comment]
It seems we need hacks (as @nils-werner put it) to actually distribute Cython code without requiring Cython as a dependency. [See this link](https://cython.readthedocs.io/en/latest/src/reference/compilation.html) for some methods.

**Comment by mrocklin** [comment]
@sklam we're only sorting unsigned integers that are the index locations of
values within a sparse array.

**Comment by hameerabbasi** [comment]
It could be `uint8`, `uint16`, `uint32` or `uint64` though.

**Comment by sklam** [comment]
good, these are the easy cases.

**Comment by nils-werner** [comment]
[I started playing around with it a little bit](https://github.com/nils-werner/sparse/blob/radixsort/radixsort.py), writing one version in NumPy, one in a Python loop and one in C++.

**Comment by hameerabbasi** [comment]
You might want to change the base to another power of two. ;-)

**Comment by nils-werner** [comment]
`np.argsort()` is still 3+ times faster

**Comment by hameerabbasi** [comment]
We could just use the SciPy implementation in this SO answer. No need to implement ourselves, no need for any kind of dependency. We could also indirectly use it to fix #60 (which I realized yesterday).

**Comment by hameerabbasi** [comment]
I was also considering using `std::vector` and Cython. Not sure if Numba transforms lists into `std::vector`s.

**Comment by rgommers** [comment]
Cython vs. Numba (vs. Pythran, vs. ...) is a hard choice (maturity and better debugging vs. beter performance and a simple decorator - plus a bunch of other considerations). The Pythran maintainer just asked about using Pythran in SciPy, for which I came up with a list of everything that needs to be evaluated: https://mail.python.org/pipermail/scipy-dev/2018-January/022334.html

> It seems we need hacks (as @nils-werner put it) to actually distribute Cython code without requiring Cython as a dependency. See this link for some methods.

Distributing generated C code in `sdist`s is not much of a hack, it has been standard practice for many libraries for a long time. At this point I'd say it has become a lot less of a necessity, because there are wheels and conda packages for all the most common platforms.

**Comment by mrocklin** [comment]
I wrote up some thoughts on the use of Numba here: http://matthewrocklin.com/blog/work/2018/01/30/the-case-for-numba

**Comment by hameerabbasi** [comment]
The problem with Numba is it doesn't accelerate `dict`s or `list`s AFAIK. That's a deal-breaker, because we need these for the most critical parts, and allocating the worst-case makes some things as bad as the worst case.

Another factor to consider is merging upstream with SciPy. I'm not sure how willing they'd be if we had Numba in our codebase.

**Comment by mrocklin** [comment]
Cython won't meaningfully update these either.  We might hope for a 2-3x speedup, but that requires significant specialization.  Instead we might intentionally search for algorithms that can be done with fixed data structures, or we might go straight to C.

FWIW it's not clear to me that we should aim to merge this into the SciPy monolith.  However I *do* think that we should aim to satisfy the same community constraints so that projects like SciPy would be willing to depend on this.  The blogpost referred to above was intended to start the conversation of "well, maybe it should be ok to depend on numba today"

**Comment by hameerabbasi** [comment]
Actually, it's simple with Cython to wrap `std::vector`, so the basic purpose of a list is fulfilled. I'd be willing to go straight to C but learning all the Python APIs would take a significant amount of time and effort, Cython sidesteps that.

**Comment by hameerabbasi** [comment]
> FWIW it's not clear to me that we should aim to merge this into the SciPy monolith. However I do think that we should aim to satisfy the same community constraints so that projects like SciPy would be willing to depend on this.

That was basically what I meant. :-)

**Comment by mrocklin** [comment]
If we we need to use C-level dynamic data structures like `std::vector` then my recommendation would be to just write algorithms in straight C and hook them up with Cython rather than writing this sort of logic in Cython itself.  

We might also look into stealing logic from Pandas, which I suspect has already had to solve a similar problem.

**Comment by hameerabbasi** [comment]
> If we we need to use C-level dynamic data structures like std::vector then my recommendation would be to just write algorithms in straight C and hook them up with Cython rather than writing this sort of logic in Cython itself.

That is actually something I had not considered before and is actually pretty viable without diving too much into the Python C API. Thanks for alerting me to it.

**Comment by mrocklin** [comment]
> If we we need to use C-level dynamic data structures

Although ideally we would find linear-time sorting algorithms for which dynamic data structures are not necessary.  I don't know this space particularly well, but I would hope that algorithms that only require fixed-size data structures exist.

**Comment by hameerabbasi** [comment]
Actually, matching (for broadcasting/binary operations) can get significant speedups from this as well, I'm playing with an implementation over at (this branch)[hameerabbasi/sparse/tree/cython-speedups].

**Comment by mrocklin** [comment]
> good, these are the easy cases.

@sklam can you recommend an algorithm for an O(n) argsort over unsigned integers?

**Comment by mrocklin** [comment]
> But if fixed size is an issue; we can always do two passes over the data: One to count and one to actually add data. Of course, this would be slow.

Two passes over an array can be much much faster than lots of allocations in dynamic data structures.

**Comment by hameerabbasi** [comment]
No harm in trying both and benchmarking. :-)

**Comment by shoyer** [comment]
> If we we need to use C-level dynamic data structures like std::vector then my recommendation would be to just write algorithms in straight C 

My "straight C" I assume you mean "straight C++"?

Anyways, I agree that straight C++ has its virtues if you want to use C++ data structures.

**Comment by hameerabbasi** [comment]
I will add that allocation will still be dynamic, even with multiple passes over the data. In the inner loop of radix sort is where we need to allocate the `std::vector` or array, not the outer one.

**Comment by mrocklin** [comment]
Do algorithms for linear-time sorting exist that use only fixed-size data structures and a reasonable number of passes?

**Comment by nils-werner** [comment]
[My experimental C++ implementation of radixsort](https://github.com/nils-werner/sparse/blob/radixsort/radixsort.py) uses fixed size data structures (but copies between them for each pass).

**Comment by hameerabbasi** [comment]
It does, however, make them bigger than they have to be... I'm not sure how much of a performance penalty this incurs, though. I haven't really tested allocation vs other operations TBH.

**Comment by nils-werner** [comment]
Since I'm only allocating needlessly large virtual memory, shouldn't the performance penalty be not too significant? Come to think of it, maybe it's not the malloc but I am raising many page faults during the actual sort run though...

I am not that experienced with actual memory management and optimization, and I haven't profiled it in detail, so I don't know.

**Comment by hameerabbasi** [comment]
That might be the reason, since you're moving between needlessly largely spaced chunks of memory. This does have the advantage of a low allocation cost (take this with a grain of salt), but it does introduce a lot of space between the (actually used part of) chunks (which is usually bad).

**Comment by hameerabbasi** [comment]
We could use [this](https://bitbucket.org/ais/usort/wiki/Home)

**Comment by hameerabbasi** [comment]
Radix sort in Numba needs `list[list]`. xref numba/numba#2560.

**Comment by mrocklin** [comment]
Alternatively could one use two passes?

**Comment by hameerabbasi** [comment]
Unfortunately, in this case, you would need either `list[list]` (or `list[ndarray]` if we used two passes), so that's not really an option right now (we can upper bound the lists and use a static `ndarray`, but the upper bound is completely unreasonable).

**Comment by mrocklin** [comment]
I haven't looked into radix sort much in the past, so please correct me if I'm saying dumb things, but some references seem to implement radix sort as just many counting sorts, each of which is computable in fixed sized data structures in two passes.

https://www.geeksforgeeks.org/radix-sort/

**Comment by hameerabbasi** [comment]
Yes, that works for radix sort, but unfortunately not for radix argsort. You would need to keep an array of indices corresponding to each modulus. In the worst case, that can be `len(arr)` long for each possible modulus, so `len(arr) * base` is the total size. To give an idea of how big the base is, `usort` uses a base of `2 ** 10` or `2 ** 11`.

**Comment by hameerabbasi** [comment]
I'm in the process of adding radix sort to NumPy. You can see the PR: numpy/numpy#12586

**Comment by hameerabbasi** [comment]
Closing this since Radix sort is in NumPy and indexing is implemented.
